# Generated by Django 4.1.6 on 2023-02-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNjokes', '0002_cnjoke_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnjoke',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
